public enum AgeRating: String, Codable, CaseIterable, Hashable, Sendable {
  case pegiThree = "pegi-three"
  case pegiSeven = "pegi-seven"
  case pegiTwelve = "pegi-twelve"
  case pegiSixteen = "pegi-sixteen"
  case pegiEighteen = "pegi-eighteen"
  case esrbRP = "esrb-rp"
  case esrbEC = "esrb-ec"
  case esrbE = "esrb-e"
  case esrbE10 = "esrb-e10"
  case esrbT = "esrb-t"
  case esrbM = "esrb-m"
  case esrbAO = "esrb-ao"
  case ceroA = "cero-a"
  case ceroB = "cero-b"
  case ceroC = "cero-c"
  case ceroD = "cero-d"
  case ceroZ = "cero-z"
}
